blank_issues_enabled: true
contact_links:
  - name: Start a New Breakout Call Series
    url: https://github.com/ethereum/pm/blob/master/processes/running-a-breakout.md
    about: Want to create a brand new breakout call? Read this guide first to understand the process and requirements.
